# Generated by Django 4.2.10 on 2024-06-06 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecipientOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('home_state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('home_state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=255)),
                ('total_passenger_capacity', models.IntegerField()),
                ('driver_volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodbank.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='TransitSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_period_of_operation', models.DateTimeField()),
                ('departure_period_of_operation', models.DateTimeField()),
                ('current_available_capacity', models.IntegerField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodbank.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('min_volunteers', models.IntegerField()),
                ('max_volunteers', models.IntegerField()),
                ('associated_food_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodbank.foodbank')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodbank.task')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodbank.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('food_group', models.CharField(max_length=50)),
                ('expiration_date', models.DateField()),
                ('item_size', models.CharField(max_length=255)),
                ('donator', models.CharField(max_length=255)),
                ('associated_food_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodbank.foodbank')),
            ],
        ),
        migrations.AddField(
            model_name='foodbank',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodbank.volunteer'),
        ),
        migrations.CreateModel(
            name='DistributedFoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodbank.fooditem')),
                ('recipient_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodbank.recipientorganization')),
            ],
        ),
    ]
