# Generated by Django 4.2.13 on 2024-06-07 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodbank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodbank',
            name='zip_code',
            field=models.CharField(default='00000', max_length=20),
        ),
        migrations.AlterField(
            model_name='foodbank',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foodbank.volunteer'),
        ),
    ]
