# Generated by Django 4.2.13 on 2024-06-09 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodbank', '0003_alter_distributedfooditem_id_alter_foodbank_id_and_more'),
        ('foodbank', '0005_rename_state_foodbank_home_state'),
    ]

    operations = [
    ]
