# Generated by Django 4.2.13 on 2024-06-09 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodbank', '0006_merge_20240608_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FoodGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='foodbank',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='foodbank.volunteer'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='donator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodbank.donator'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='food_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodbank.foodgroup'),
        ),
    ]
