# Generated by Django 4.2.13 on 2024-06-10 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbank', '0007_donator_foodgroup_alter_foodbank_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date_time',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 12, 0)),
        ),
        migrations.AlterField(
            model_name='task',
            name='max_volunteers',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='min_volunteers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date_time',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 9, 0)),
        ),
    ]
