# Generated by Django 4.2.13 on 2024-06-10 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodbank', '0008_alter_task_end_date_time_alter_task_max_volunteers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndividualShift',
            new_name='Volunteer_Task',
        ),
    ]
