# Generated by Django 4.2.10 on 2024-06-11 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodbank', '0012_alter_transitschedule_arrival_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='donator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodbank.donator'),
        ),
    ]
